sudo: required
services:
  - docker
jobs:
  include:
    - stage: Build and Push Docker Images
      script:
        # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd jupyter_docker && bash build.sh && cd ..
        # run tests
        - cd jupyter_docker && DOCKER_USER="root" bash runtest.sh && cd ..
        # push if tests where successful (later)
    - stage: deploy
      language: python
      python: 3.6
      install:
        - cd pacsltk
        - pip install -r requirements.txt
        - pip install .
        - cd ..
      before_deploy:
        # convert README file
        - source .travis/build.sh
      # deploy:
      #   provider: pypi
      #   user: nima_mahmoudi
      #   distributions: sdist bdist_wheel
      #   skip_existing: true
      #   skip_cleanup: true
      #   # To add password, do the following: travis encrypt your-api-token --add deploy.password --com
